services:
  - type: web
    name: library-borrow-server
    runtime: node
    plan: free
    region: singapore
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        value: postgresql://neondb_owner:npg_9zMP3KrjaNQl@ep-purple-sound-azq3acvy.c-3.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

  - type: static
    name: library-borrow-frontend
    plan: free
    region: singapore
    buildCommand: npm install && npm run build
    publishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://library-borrow-server.onrender.com
